import math
a = int(input())
b = int(input())
print("Sum:" + str(a+b))
print("Difference: " + str(b-a))
print("Product: " + str(a*b))
print("Quotient: " + str(a/b))
print("Remainder: " + str(a % b))
print("Log10 of first number: " + str(math.log10(a)))
print(str(a)+str(b))
